apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  uid: loki
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false

- name: Tempo
  type: tempo
  access: proxy
  uid: tempo
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    nodeGraph:
      enabled: true
    serviceMap:
      datasourceUid: 'Prometheus'
    tracesToLogs:
      datasourceUid: loki
      filterByTraceID: false
      spanEndTimeShift: "500ms"
      spanStartTimeShift: "-500ms"

- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
